# map of Sentry python packages to apt packages, maintained manually
package_map = {
    'BeautifulSoup': 'python-beautifulsoup',
    'celery': 'python-celery',
    'cssutils': 'python-cssutils',
    'Django': 'python-django',
    'django-bitfield': 'python-django-bitfield',
    'django-crispy-forms': 'python-django-crispy-forms',
    'django-jsonfield': 'python-django-jsonfield',
    'django-picklefield': 'python-django-picklefield',
    'djangorestframework': 'python-djangorestframework',
    'enum34': 'python-enum34',
    'gunicorn': 'gunicorn',
    'ipaddr': 'python-ipaddr',
    'lxml': 'python-lxml',
    'mock': 'python-mock',
    'markdown': 'python-markdown',
    'progressbar': 'python-progressbar',
    'pytest': 'python-pytest',
    'python-dateutil': 'python-dateutil',
    'redis': 'python-redis',
    'simplejson': 'python-simplejson',
    'six': 'python-six',
    'setproctitle': 'python-setproctitle',
    'statsd': 'python-statsd',
    'South': 'python-django-south',
    'urllib3': 'python-urllib3',
    'psycopg2': 'python-psycopg2',
}
